name: quicko_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Shared Preferences for settings
  shared_preferences: ^2.2.2
  
  # Audio
  audioplayers: ^5.2.1
  
  # Image Generation and Sharing
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  
  # AdMob for Rewarded Ads
  google_mobile_ads: ^6.0.0
  
  # In-App Purchase
  in_app_purchase: ^3.1.13

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

  # URL Launcher for email functionality
  url_launcher: ^6.2.5

  # HTTP for EmailJS API calls
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/icon/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/quicko.png"
  adaptive_icon_background: "#6B46C1"
  adaptive_icon_foreground: "assets/icon/quicko-removebg.png"
  min_sdk_android: 23
  web:
    generate: true
    image_path: "assets/icon/quicko.png"
    background_color: "#6B46C1"
    theme_color: "#6B46C1"
  windows:
    generate: true
    image_path: "assets/icon/quicko.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/quicko.png"

flutter_native_splash:
  color: "#B794F4"
  color_dark: "#B794F4"
  
  image: assets/icon/quicko-removebg.png
  image_dark: assets/icon/quicko-removebg.png
  
  android_12:
    image: assets/icon/quicko-removebg.png
    image_dark: assets/icon/quicko-removebg.png
    color: "#B794F4"
    color_dark: "#B794F4"
    icon_background_color: "#B794F4"
    icon_background_color_dark: "#B794F4"
  
  web: false
