name: quicko_app
description: "Quicko"
publish_to: 'none' 
version: 1.0.0+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  
  # Shared Preferences for settings
  shared_preferences: ^2.2.2
  
  # Audio
  audioplayers: ^5.2.1
  
  # Image Generation and Sharing
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  
  # AdMob for Rewarded Ads
  google_mobile_ads: ^6.0.0
  
  # In-App Purchase
  in_app_purchase: ^3.1.13

  # Firebase
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.4.4

  # URL Launcher for email functionality
  url_launcher: ^6.2.5

  # HTTP for EmailJS API calls
  http: ^1.1.0

  # Country picker for selecting country with flags
  country_picker: ^2.0.26

  # Internet connectivity
  connectivity_plus: ^5.0.2

  # Lottie animations
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/icon/
    - assets/logo/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  generate: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/logo/quality_icon.png"
  image_path_android: "assets/logo/quality_icon.png"
  adaptive_icon_foreground: "assets/logo/quality_icon.png"
  adaptive_icon_background: "assets/logo/quality_icon_bg.png"
  remove_alpha_ios: true
  min_sdk_android: 23


flutter_native_splash:
  color: "#8E44AD"
  color_dark: "#8E44AD"
  
  image: assets/logo/quality_icon.png
  image_dark: assets/logo/quality_icon.png
  
  android_12:
    image: assets/logo/quality_icon.png
    image_dark: assets/logo/quality_icon.png
    color: "#8E44AD"
    color_dark: "#8E44AD"
    icon_background_color: "#8E44AD"
    icon_background_color_dark: "#8E44AD"
  
  web: false
